### ISSUE TITLE
Cannot download checkpoint from git-lfs: This repository is over its data quota.

### ISSUE THREAD

**Issue by lhlmgr** [hellochick/PWCNet-tf2#3]
Hi there,
Thanks for your implementation of PWC. Unfortunately, I'm not able to download the checkpoint from git-lfs since the data quota is over for your repository.

```
➜  PWCNet-tf2 git:(master) ✗ git lfs pull
Git LFS: (0 of 1 files) 0 B / 107.28 MB                                        
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/hellochick/PWCNet-tf2.git/info/lfs'
```
Would it be possible to upload the checkpoint somewhere else? I Would really appreciate it!
Thanks in advance!

**Comment by hellochick** [comment]
Hi @lhlmgr ,

I just bought some data quota, could you try one more time to download the checkpoint?

**Comment by lhlmgr** [comment]
Wow.. thanks a lot!
It works now!

```
git clone https://github.com/hellochick/PWCNet-tf2
Cloning into 'PWCNet-tf2'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 47 (delta 15), reused 36 (delta 9), pack-reused 0
Unpacking objects: 100% (47/47), done.
```

Thanks again!

**Comment by hellochick** [comment]
No problem!

Just a reminder, the codes in this repository may need some change to reproduce the test result presented in the original paper.

**Comment by ngocnh22** [comment]
Hi @hellochick,

How to solve this problem? How did you buy some data quota? 
Thank you for your reply!

**Comment by AlbertHuyb** [comment]
> Hi @hellochick,
> 
> How to solve this problem? How did you buy some data quota? Thank you for your reply!

You can download the git-lfs files with the solution provided [here](https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh/68113604#68113604?newreg=90e8ffac7c9749009f2228e912bf6341).

**Comment by hellochick** [comment]
@ngocnh22 @AlbertHuyb 
I've updated the repo with the script for downloading models.
Thank you for commenting!
